### ISSUE TITLE
Figure out/ Insert ArcGIS SmartMapping code for a chloropleth map

### ISSUE THREAD

**Issue by adamajm** [CORaleigh/dataviz_search#6]
For Construction Permit widget (Row 395): https://github.com/CORaleigh/dataviz_search/blob/Adam-Mods/Static_Widgets/styleguide/templates/widget-construction-permitting.html

Leverage SmartMap API https://developers.arcgis.com/javascript/3/jsapi/esri.renderers.smartmapping-amd.html

Where we can serve up GEOID for Census Block Groups and a Value (via SODA API) and result in a chloropleth map in our widget.

DATA coming from here (currently a private dataset so will need to authenticate): https://data.raleighnc.gov/resource/c4sh-s8ap.json

Row 395:
    <div class="panel">
        <header>
            <h2 class="panel__title">$ Amount of Construction Planned in Past One Year</h2>
        </header>
        <div class="panel__content panel__content--dark-blue">
            
            <div id="arcgis-map" class="arcgis-map">

```
            <div style="text-align: center; padding: 50px 0">[census map placeholder]</div>
            <!--
                colors from design:
                dark blue: #3e63a3
                medium blue: #5986d3
                light blue: #80adfc
            -->

        </div>
```

**Comment by justingreco** [comment]
Suggest that we just store this as a static JSON file until the dataset is made public so we don't need to worry about the authentication piece.

**Comment by justingreco** [comment]
The GEOID10 attributes are not matching any of the block groups in Wake County.  What dataset did you get those from?

**Comment by adamajm** [comment]
this dataset shd be public now so no auth needed: https://data.raleighnc.gov/OData.svc/9cr5-i8d2

**Comment by adamajm** [comment]
Justin has provided a working prototype of Geolocation and chloropleth map at this branch: https://github.com/CORaleigh/dataviz_search/tree/censusmap

For those on COR network, this can be seen on test server when you search for "census" 
http://gsatst.ci.raleigh.nc.us/search?q=census&btnG=Search&client=COR_WEB&proxystylesheet=COR_WEB&ulang=en&sort=date%3AD%3AL%3Ad1&wc=200&wc_mc=1&oe=UTF-8&ie=UTF-8&ud=1&exclude_apps=1&site=portalprd&tlen=255#

Geolocation works on Firefox, and will on chrome when SSL is installed on server.
